name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build-and-check:
    name: Build & Bundle Size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_STELLAR_NETWORK: testnet
          NEXT_PUBLIC_STELLAR_RPC_URL: https://soroban-testnet.stellar.org
          NEXT_PUBLIC_STELLAR_HORIZON_URL: https://horizon-testnet.stellar.org
          NEXT_PUBLIC_STELLAR_NETWORK_PASSPHRASE: "Test SDF Network ; September 2015"
          NEXT_PUBLIC_INVOICE_CONTRACT_ID: CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4
          NEXT_PUBLIC_MARKETPLACE_CONTRACT_ID: CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4
          NEXT_PUBLIC_TOKEN_CONTRACT_ID: CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABSC4
          NEXT_PUBLIC_IPFS_GATEWAY: https://gateway.pinata.cloud/ipfs
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          NEXT_PUBLIC_ENABLE_MOCK_DATA: "false"
          NEXT_PUBLIC_ENABLE_DEVTOOLS: "false"

      - name: Check bundle size
        run: npx bundlesize
